### ISSUE TITLE
Expose account bandwidth and tron power in the popup

### ISSUE THREAD

**Issue by tayler-king** [TronLink/tronlink-extension#136]
Need to be able to access `account.bandwidth` and `account.tronPower`.

@metjm will need to implement the API for this, and @Kondax can add the fields to the account objects and update the transactions page.

**Comment by tayler-king** [comment]
Balance can be found from `/wallet/getaccountnet`. This should be updated in the `wallet.updateAccount` method @metjm

**Comment by tayler-king** [comment]
Fixed in v2

**Comment by DelsonStrike** [comment]
Hello, I do not see my wallet. The window is just empty. I tried to restore access using the private key, but it throws me at my address, and the balance is also empty, can you help?
