### ISSUE TITLE
Add freeze / unfreeze functionality in the popup

### ISSUE THREAD

**Issue by tayler-king** [TronLink/tronlink-extension#157]
This should be added to the right of the account balance.

If the user does not hold any TP only show the "freeze" button. If they hold TP show the freeze button along with "Unfreeze", giving the expiration date (whether it be in the future or the past).

This could potentially be stacked, with a seperation line between them. 

@metjm will work on the blockchain interaction, and @Kondax will add the two buttons.

Either @Kondax or @tpudel can add the transaction types to the transaction list if they do not already exist.

**Comment by tayler-king** [comment]
Fixed in v2.

**Comment by DelsonStrike** [comment]
Hello, I do not see my wallet. The window is just empty. I tried to restore access using the private key, but it throws me at my address, and the balance is also empty, can you help?
