### ISSUE TITLE
Chrome Tokens Tab Issue 

### ISSUE THREAD

**Issue by sticklerlangki5** [TronLink/tronlink-extension#199]
Dear Sir/Madam

I have found out that in the Token tab on the TronLink is having a problem in displaying all the tokens.
Some of the Tokens goes missing because there is no scroll .
I have attached an image along to show the error . Please do look into this error.

![47517322-75103500-d8a5-11e8-98d3-ec2e518d433e](https://user-images.githubusercontent.com/788421/47559427-0f6a8a00-d933-11e8-9ecd-0806feb11e08.PNG)

Trx address: TRvDKmckJtRmYGb3A7EFU5uBL6pkRM2w7G

Thanking You.

**Comment by tayler-king** [comment]
Fixed in v2

**Comment by sticklerlangki5** [comment]
Great news.

Keep it up.

Go tron.
