### ISSUE TITLE
Coinbase Pro Issue

### ISSUE THREAD

**Issue by amn357** [TronLink/tronlink-extension#200]
Hey I just jumped on here to let you know there is an issue with tronlink and coinbase pro website. I added the tronlink extension then when I visited coinbase pro all was well till i placed an order, the whole page would become unresponsive. After going at it with CB support. Removing Tronlink extension solved the problem as it was the only new thing I added to the browser. HEADSUP!!

**Comment by tayler-king** [comment]
Hmm, we can definitely take a look into this but I highly doubt it's the issue. TronLink doesn't interfere with the website in any way until the website attempts to access it - apart from the initial start up.

**Comment by amn357** [comment]
Im sorry but it does. I tried installing Tronlink again and the problem
came back. Had to remove the extension. Sucks because other than that it
worked perfectly.
*Angel Neris SL#3293576*
*Living Realty PB llc *
*125 Sycamore Dr.*
*Royal Palm Beach, FL 33411*

**Comment by tayler-king** [comment]
Fixed in v2.
