### ISSUE TITLE
TronWeb returns decimals as object

### ISSUE THREAD

**Issue by kolya-t** [TronLink/tronlink-extension#221]
If return value of contract function is named (as in example below)
``` solidity
function decimals() public pure view returns (uint8 _decimals) {
  return 18;
}
```
then tronWeb will return ```{_decimals: 18}``` instead ```18```.

You have to handle this and extract decimals number from object if needed. Because now TRC20 contract with decimals function with named return value cannot be imported to wallet. TronLink freezes and become gray when I'm trying to add token with such function.
![image](https://user-images.githubusercontent.com/11293491/50784807-d1d59600-12bf-11e9-84e6-904b812db76d.png)

**Comment by tayler-king** [comment]
This could be fixed quite easily - but is there a reason you'd use a named return value for the decimals prop?

**Comment by kolya-t** [comment]
Some developers make all return values named in Solidity code. There is no reasons to not support them.

**Comment by kolya-t** [comment]
Our smart contracts platform (http://github.com/MyWishPlatform) creates TRC20 tokens with named return value in decimals(). We can change it, but old tokens will not be supported by TronLink.

**Comment by tayler-king** [comment]
Oh yeah, definitely no reason not to support them. Was just curious as to why you would. 

Not sure if it would be beneficial to do this in TronWeb instead - if there's only one output, it doesn't make sense to return an object. @sullof Do you think this should be changed in TronWeb instead?
