### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by shipunyc** [TronLink/tronlink-extension#225]
![image](https://user-images.githubusercontent.com/8388829/51048794-fa98ac80-1599-11e9-8883-588fa0c1d8b6.png)

I'm developing a dApp, and used tronlink to access smart contracts.

What's wrong? It seems my domain name is not in the whitelist?

**Comment by tayler-king** [comment]
This is an issue with TronGrid. I'd suggest using a different node provider, such as Guildwallet.
