### ISSUE TITLE
Future support of TronLink Chrome extension

### ISSUE THREAD

**Issue by travek** [TronLink/tronlink-extension#228]
Hello!

Following the news about Tron Desktop Wallet deprecation I have the following question to the team. Will the team continue to support and develop Tronlink Chrome extension wallet ? Are the news about deprecation of Tron Desktop impacting TronLink Chrome ?

Thanks

**Comment by tayler-king** [comment]
TronLink is a separate project from TronWatch Desktop Wallet, and will not be affected by the deprecation of the desktop wallet.
