### ISSUE TITLE
Voting functionality support

### ISSUE THREAD

**Issue by travek** [TronLink/tronlink-extension#229]
Hi!

I installed TronLink Chrome extension.
Is it possible to vote in this Chrome app? If yes, where's this functionality ?
If NO, when it is supposed to be supported according to the current roadmap ?

**Comment by tayler-king** [comment]
Not currently supported

**Comment by travek** [comment]
@Kondax , will it be supported in the future ? Are there any plans to support this feature and when ?

**Comment by tayler-king** [comment]
I am not sure, I no longer maintain TronLink

**Comment by travek** [comment]
ZacharyLe, Team,
what are current plans to support voting and freezing in TronLink ?

**Comment by travek** [comment]
ALL,
when we can have voting and freezing functionality in TronLink ?

**Comment by travek** [comment]
Up
when we can have voting and freezing functionality in TronLink ?
