### ISSUE TITLE
Cant log in to TL

### ISSUE THREAD

**Issue by LongTronSilver** [TronLink/tronlink-extension#235]
Hi,
I cannot login to my TL wallet it keeps telling me, "Account Unlock Failed- account already unlocked",        When I first log in, the wallet is blank and grey, not showing account ect, then if i refresh or close and reopen  (chrome) browser, I get the above message

**Comment by dehmke** [comment]
I'm having the exact same issue.  I noticed it happened after I had mistakenly entered in an incorrect node address, logged out and then tried to log back in.  Unfortunately I can't find my recovery phrase or I'd simply reinstall the extension.  I was hoping that the node addresses were saved in the source files, but no dice.  Any help would be appreciated.

<img width="411" alt="tronlink error" src="https://user-images.githubusercontent.com/191675/52284395-50127000-2932-11e9-80de-73504274f1b6.png">

**Comment by zk19862018** [comment]
please try the new version
