### ISSUE TITLE
The Pending Transactions

### ISSUE THREAD

**Issue by nishuzumi** [TronLink/tronlink-extension#237]
I found a problem. If the user closes the pop-up transaction request, the program can't handle it correctly like click rejection or accept, and the next time the transaction box pops up, the last unfinished request will be displayed first. Then how can I clear these requests? , or how to capture the event that the user closes the popup directly?

**Comment by tayler-king** [comment]
This isn't currently handled, it will just stay in the queue and the user will have to reject it the next time. It should be fixed so that closing the popup will reject the confirmation
