### ISSUE TITLE
TronLink sign a string message 

### ISSUE THREAD

**Issue by wushbin** [TronLink/tronlink-extension#239]
Hi there, 
I would like to know is there an API in tronlink that I can sign a verification string message without exposing a user's private key. That means I could use tronlink to sign a message like the features in scatterjs and eth web3 as the links below. 

[web3js sign](https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign)
[scatterjs sign](https://get-scatter.com/docs/api-request-arbitrary-signature)

Thanks

**Comment by tayler-king** [comment]
Yes, `tronWeb.trx.sign(hex)`

**Comment by wushbin** [comment]
@Kondax  thanks.

**Comment by wushbin** [comment]
@Kondax  Hi, Kondax. So after signing the data using `tronWeb.trx.sign(hex)`. Is there a way that I could verify this signed data with the user's public key? 
Like ecc.verify in eos and ecrecover in eth.

**Comment by tayler-king** [comment]
`tronWeb.trx.verifyMessage(x)`

**Comment by ghost** [comment]
`tronWeb.trx.verifyMessage(tronWeb.trx.sign(hex))` returns true on desktop browser (tronlink browser extension), but when I use 
it with tronlink android application (it uses the same api), it returns false, so it seems verify function doesnt much sign function when using with TronLink mobile application. Could you help me please with it  

I covered it in #283 could you help me to figure this out please

**Comment by Aziz87** [comment]
@SergeyAnkarenko, Привет! Не разобрался?
Как сделать верификацикацию подписанного ключа...

**Comment by tntdev21** [comment]
For anyone who come here later:
- to sign a hex message: `tronWeb.trx.sign(hexMessage)`
- to verify that message is signed from an address, you'll need:

1. The `hexMessage`
2. The `signature`
3. The `address` that sign the message
Then:
```
tronWeb.trx.verifyMessage(hexMessage, signature, address)
```
I found it in [source code](https://github.com/tronprotocol/tronweb/blob/master/src/lib/trx.js#L605)

**Comment by kimgysen** [comment]
@CQBinh Why do the docs say not to use this? How else to sign a message on the client? 

<img width="714" alt="Screenshot 2021-12-11 at 09 54 08" src="https://user-images.githubusercontent.com/4547364/145670694-f662f5b3-d9a8-4179-9214-1ff91aabee44.png">

**Comment by tntdev21** [comment]
@kimgysen on client side, you can use providers like metamask to sign the message, so you don't need to pass the privagte key to `.sign()` method.

If you sign on server side, you'll need to pass the private key.

**Comment by kimgysen** [comment]
@CQBinh Thanks. Yes I misinterpreted what they mention, didn't realise they were referring to the private key in source code rather than the method itself.
