### ISSUE TITLE
Crashing while adding TRC20 Token on shasta network

### ISSUE THREAD

**Issue by tokyo786** [TronLink/tronlink-extension#240]
Hi, TronLink Crashes while adding TRC20 Token on shasta test network.

Steps to reproduce bug:

Install TronLink
Point to Shasta Testnet
Add TDJHsqk8Rnp5P6c8Em8YD54ipFdKtzS4Di as a TRC20 Token
Click the back icon
You see a white screen

![image](https://user-images.githubusercontent.com/19167384/54045792-89235600-41f8-11e9-9038-bb54f496fbcf.png)

![image](https://user-images.githubusercontent.com/19167384/54045838-a3f5ca80-41f8-11e9-9073-42b735461447.png)

![image](https://user-images.githubusercontent.com/19167384/54045892-c7207a00-41f8-11e9-97db-23bd087e7c62.png)

**Comment by ZacharyLe** [comment]
We have resolved this issue at version of 2.1.9.2 and 2.1.9.3

**Comment by ZacharyLe** [comment]
Can you provide the two contract addresses ? Because it is convinent for us to find where is the question.
