### ISSUE TITLE
adding redeployed token

### ISSUE THREAD

**Issue by ibnzUK** [TronLink/tronlink-extension#242]
Our old contract had a little error in the code so before we start redistribution of our token we fixed few errors and redeployed new token. 
Now It is a new contract but the name of the token is still the same.

When trying to add new token on tronlink manually it gives an error message (because old token with the same name is already added) 

![image](https://user-images.githubusercontent.com/48181667/54146649-5a8bc200-4428-11e9-986b-69b0a1c755f9.png)

**Comment by ZacharyLe** [comment]
Ok,I got it, I'm sorry for that case,  we discriminate different trc20 tokens from name or abbreviation,we will republish a new version to resolve it.

**Comment by ZacharyLe** [comment]
Can you provide the two contract addresses for us to locate where is the bug?

**Comment by ZacharyLe** [comment]
Resolved
