### ISSUE TITLE
iframe环境中，无法获得window.tronWeb对象

### ISSUE THREAD

**Issue by snoopy1412** [TronLink/tronlink-extension#243]
部分应用需要在iframe环境中执行，但是window.tronWeb一直未undefined,而tronPay，以及以太坊钱包metamask都没问题，想请教一下如何设置，还是后续添加对应的许可？

**Comment by ZacharyLe** [comment]
这边需要对minifest.json做一下修改就可以，对iframe进行支持，但是考虑到一些极特殊的情况，没有放开那个配置，待我们商议过后，做出答复，但是现在可以通过postMessage的方式，解决tronweb的访问问题

**Comment by ZacharyLe** [comment]
We has resolved this issue, you can get object tronWeb any iframes.
