### ISSUE TITLE
Error Message not formatted 

### ISSUE THREAD

**Issue by ibnzUK** [TronLink/tronlink-extension#244]
When trying to send the same token and balance is empty error message is a bit ugly

![image](https://user-images.githubusercontent.com/38762355/54277696-7c9c5600-4588-11e9-8e79-14ae15e3578e.png)

**Comment by ZacharyLe** [comment]
Thanks for your opinion, I will do with it by adding some friendly tips.

**Comment by ZacharyLe** [comment]
It is improssibly visible the ugly interface.
