### ISSUE TITLE
Transaction amount mismatch. Decimal point error

### ISSUE THREAD

**Issue by ibnzUK** [TronLink/tronlink-extension#245]
trc10 token amount in transaction history displayed wrong. Incorrect decimal point.
below are two screenshots from tronlink and tronscan 

![image](https://user-images.githubusercontent.com/38762355/54277806-bf5e2e00-4588-11e9-8e77-f0a939370058.png)
![image](https://user-images.githubusercontent.com/38762355/54277842-d43ac180-4588-11e9-8e42-12148cf0507a.png)

**Comment by ZacharyLe** [comment]
This issue has been fixed.

**Comment by ZacharyLe** [comment]
This issue has been fixed.
