### ISSUE TITLE
TronLink failed to inject window.tronWeb

### ISSUE THREAD

**Issue by olegabr** [TronLink/tronlink-extension#248]
In browser console:

```
[Apr 16, 02:11:27 am] [contentScript]: [INFO]: TronLink injected
alpha.js:13 Uncaught SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class
    at Object.../../node_modules/validator/lib/alpha.js (alpha.js:13)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/validator/lib/isAlpha.js (isAlpha.js:11)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/validator/index.js (index.js:36)
    at __webpack_require__ (bootstrap:19)
    at Object.../../node_modules/tronweb/dist/TronWeb.node.js.module.exports (TronWeb.node.js:1)
    at n (TronWeb.node.js:1)
    at Module.<anonymous> (TronWeb.node.js:1)
    at n (TronWeb.node.js:1)
```

Browser:

```
Chromium
Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
```

System:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

I'm having the same error if trying to use tronweb.js directly in a browser. But it can be fixed if I comment out these lines:

```
 // 'el-GR': /^[Α-ω]+$/i,
```

They are defined in the `exports.alpha = alpha;` and `exports.alphanumeric = alphanumeric;`

**This error is important because it blocks the TronLink usage in dapps completely.**

**Comment by tayler-king** [comment]
Set the charset in your HTML using a meta tag - `utf-8`.

**Comment by szandras2524** [comment]
> In browser console:
> 
> ```
> [Apr 16, 02:11:27 am] [contentScript]: [INFO]: TronLink injected
> alpha.js:13 Uncaught SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class
>     at Object.../../node_modules/validator/lib/alpha.js (alpha.js:13)
>     at __webpack_require__ (bootstrap:19)
>     at Object.../../node_modules/validator/lib/isAlpha.js (isAlpha.js:11)
>     at __webpack_require__ (bootstrap:19)
>     at Object.../../node_modules/validator/index.js (index.js:36)
>     at __webpack_require__ (bootstrap:19)
>     at Object.../../node_modules/tronweb/dist/TronWeb.node.js.module.exports (TronWeb.node.js:1)
>     at n (TronWeb.node.js:1)
>     at Module.<anonymous> (TronWeb.node.js:1)
>     at n (TronWeb.node.js:1)
> ```
> 
> Browser:
> 
> ```
> Chromium
> Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
> ```
> 
> System:
> 
> ```
> $ cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
> ```
> 
> I'm having the same error if trying to use tronweb.js directly in a browser. But it can be fixed if I comment out these lines:
> 
> ```
>  // 'el-GR': /^[Α-ω]+$/i,
> ```
> 
> They are defined in the `exports.alpha = alpha;` and `exports.alphanumeric = alphanumeric;`
> 
> **This error is important because it blocks the TronLink usage in dapps completely.**

In which file is this defined? I couldn't find it ! Thank you!
