### ISSUE TITLE
TronLink 2.2.5 security issue & breaking changes

### ISSUE THREAD

**Issue by hiendv** [TronLink/tronlink-extension#251]
I did not notice about the version bumps recently but the bug is reproducible with TronLink 2.2.5 and possibly earlier versions.

1. Make sure you're already logged in TronLink
2. Log out
3. Trigger smart contracts successfully (which should be forbidden)
4. The wallet is now magically logged in

The breaking changes also effect normal behaviors. e.g. listening to `addressChanged` event.

**Comment by hiendv** [comment]
It's a security issue guys. At least you can publish the source code so we can send a PR fixing this.

**Comment by zk19862018** [comment]
Please try the latest version. And we are open source.

**Comment by hiendv** [comment]
I know you are. But back then when I found the bug, 2.2.5 is released but not published to Github.
