### ISSUE TITLE
Deploy fail! Error while Smart Contract deployment to Shasta & MainNet

### ISSUE THREAD

**Issue by VanijaDev** [TronLink/tronlink-extension#254]
I am Ethereum and Tron Smart Contracts dev. I face a strange issue with TronLink today… I get error: Deploy fail! Error: TypeError: Object.defineProperty called on non-object during the deployment of any smartContract using https://tronsmartcontract.space/#/compose service. It used to work well a few days ago. 
Does any1 experience same problems and… do you have workarounds? 
TronLink version: 2.4.4 (the latest)
Chrome: Version 74.0.3729.157 (Official Build) (64-bit)
MacOS

**Comment by ZacharyLe** [comment]
Maybe it doesn't work, while you deployed smart contract, you can use our product tron-box that it promises the contracts security.
