### ISSUE TITLE
I am seeing token created on testnet while mainnet selected

### ISSUE THREAD

**Issue by ibnzUK** [TronLink/tronlink-extension#255]
I created test token on testnet but able to see on my wallet while on mainnet. 
balance shows 0 but still enoying. 

Token contract address : TF3EVzLEjhDSeX5u2QftWrhYjDPRbKxaYc , doesnt even exist on mainnet

![image](https://user-images.githubusercontent.com/38762355/58621652-cfe98f00-82c1-11e9-93f3-930ed25b7cad.png)
![image](https://user-images.githubusercontent.com/38762355/58621680-dbd55100-82c1-11e9-8dcf-42bfcd697574.png)

![image](https://user-images.githubusercontent.com/38762355/58621909-4e463100-82c2-11e9-804e-47b5cafaf558.png)

**Comment by ZacharyLe** [comment]
Yes，it is an issue that exists really , because you are manual operation a trc20 token in shast , I should save it even you switch mainnet in case of switching back shast.  I will resolve it if the team has this plan.

**Comment by zk19862018** [comment]
please try the new version.
