### ISSUE TITLE
TronLink doesn't show token amount when triggering contract

### ISSUE THREAD

**Issue by ColonelJ** [TronLink/tronlink-extension#256]
Hi, when triggering a smart contract using a TRC10 token, it shows the ID of the token but it doesn't show the amount, so you have no idea how much of your token you're going to spend if you accept the transaction.

This is a big usability issue and risks unexpectedly losing tokens if using an unscrupulous website.

When triggering using a TRX amount this is shown correctly, it is only TRC10 that isn't shown.

**Comment by ZacharyLe** [comment]
Thanks for your good suggest, this is a bug of product  design, we will resolve it as soon as possible.

**Comment by ColonelJ** [comment]
Why did you close this?  It still hasn't been fixed.  It is very important to show this information.
