### ISSUE TITLE
TronLink is not found in chrome store

### ISSUE THREAD

**Issue by gologo13** [TronLink/tronlink-extension#257]
Hi, I tried to install TronLink on my Chrome, but I couldn't access to it.
I found the chrome extension is not found here:
https://chrome.google.com/webstore/detail/ibnejdfjmmkpcnlpebklmnkoeoihofec

Google says `404. That’s an error. The requested URL was not found on this server. That’s all we know.`.
Could you check if it's available to public.
thanks in advance.

**Comment by Magalon** [comment]
Hi, @gologo13 Thanks for the report.

We are currently in discussion with Google to know what happens on that side.

We will keep you posted as soon as the situation is fixed.

**Comment by Magalon** [comment]
Everything is now back to normal.

Thanks for the report.

**Comment by gologo13** [comment]
thank you for the quick fix!
