### ISSUE TITLE
Quantity on popup doesn't match for TRC10 transfers

### ISSUE THREAD

**Issue by NoahCardoza** [TronLink/tronlink-extension#318]
I'm not sure if this is something I just understand about Tron or this is a bug.

![image](https://user-images.githubusercontent.com/10343470/122441064-07cbd980-cf52-11eb-957c-c8db5140cb2f.png)

![image](https://user-images.githubusercontent.com/10343470/122441080-0d292400-cf52-11eb-9108-a599915faa35.png)

Note I only want to send 3.8 coins out but Tron Link is saying I'm trying to send 3,800,000 coins? It should also be noted that the transactions always result in a success.

**Comment by Crypto2** [comment]
It is showing incorrect balances for me on TRC10 tokens as well.

**Comment by sclihuiming** [comment]
The question mark after the number has an explanation, this is because the precision of the token was not obtained, from the screenshot, the precision of the token is 6 bits, so 3.8 -> 3.8 * 1000000 = 3800000
