### ISSUE TITLE
Import account screen

### ISSUE THREAD

**Issue by metjm** [TronLink/tronlink-extension#37]
When a user goes to the import screen they're have 4 options:

- Import from TronWatch
- Import from TronScan
- Import from word list
- Import from private key

Each one will need a basic description so users know which to pick (we'll write this later)

Then we'll need a page for each one (I think we have private key already done?)

TronWatch will have 24 word import
TronScan will have a textarea to paste keystore file, and if doable (I think we can with chrome extension) upload button to upload keystore file
Word list will have 24 word import
Private key will just have the text input

If you want to do any of those then feel free to.

For TronWatch we'll have the 24 seperate boxes. I suggest using this code: https://github.com/TronWatch/Seed-Recovery/blob/master/src/index.js#L115
instead of desktop code as the desktop method was an absolute mess. The code above renders 24 inputs, going left down to right down (like tronwatch desktop)

For the word list I'd rather just have a textarea to paste the words in

**Comment by tayler-king** [comment]
@tpudel
