### ISSUE TITLE
Address funding for the testnet

### ISSUE THREAD

**Issue by metjm** [TronLink/tronlink-extension#42]

**Comment by tayler-king** [comment]
Can do this by calling the tronscan free 10,000 trx endpoint?

**Comment by metjm** [comment]
nope, that endpoint requires a captcha, and also its not our private testnet. its a public one

**Comment by tayler-king** [comment]
That's true. Tronscan is open source anyway, so you should be able to do a "near" copy-paste job?

**Comment by metjm** [comment]
the TronUtil has a function that is just sendTron(address, amount), its super easy to do. The question is only where to do it, either we do it super lazy and just put the private key for the account holding all coins into the extension and send it straight from there, or we make an endpoint somewhere... maybe google cloud functions

**Comment by tayler-king** [comment]
I'd recommend an endpoint so that we still have full access of the account

**Comment by metjm** [comment]
https://us-central1-flottpay.cloudfunctions.net/testCoins?address=TBRhZaCdcERsmkBTMMf3C7rbvazVVD63ee

^endpoint, we need a butotn in the extension to trigger it.

**Comment by DelsonStrike** [comment]
Hello, I do not see my wallet. The window is just empty. I tried to restore access using the private key, but it throws me at my address, and the balance is also empty, can you help?

**Comment by metjm** [comment]
Hi, I assume you're talking about the desktop wallet @DelsonStrike  
It has been deprecated since January (https://github.com/TronWatch/Desktop-Wallet/issues/165), and the reason why your balance looks empty is because we finally shut down the servers. 
You can use any of the other wallets here: https://tron.network/wallet with your private key to access your funds.

If you need further assistance, please contact us on telegram: https://t.me/TronWatch

**Comment by DelsonStrike** [comment]
My private key does not work on other wallets.

пт, 21 июн. 2019 г. в 04:38, metjm <notifications@github.com>:

**Comment by DelsonStrike** [comment]
Hello, I had lost access my balance (TGyAPLf9H2UY9UTfZyCAmAPVAse6Ukn8rr) at
17 of june. When my the desktop tron wallet stopped working, I lost access
to my wallet which was created by me a long time ago, therefore from the
data I only have a private key but it does not work on other wallets, I had
a password when I created this wallet, an account name and a photo of the
fact that this wallet is mine (the photo is old but it shows the balance
that was the and address). I can show you any proof if ask to proove that
the wallet is really mine. Please help me to get access to my coin, I sold
everiting to buy this coins. Now I dont know what I should do. I used the
old version of the throne and did not see the words and the private key.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пт, 21 июн. 2019 г. в 04:38, metjm <notifications@github.com>:
